config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  resources :cards, except: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord

  validates :translated_text, :review_date, presence: true
  validates :original_text, presence: true, uniqueness: true
  validates_with OriginalAndTranslatedTextFieldsNotEqualValidator

  before_validation :capitalize_fields_and_create_review_date

  private

  def capitalize_fields_and_create_review_date
    self.original_text = original_text.to_s.strip.capitalize
    self.translated_text = translated_text.to_s.strip.capitalize
    self.review_date = Time.now + 3.days unless review_date
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: %i[edit update destroy]

  def index
    @cards = Card.all.order(:id)
  end

  def new
    @card = Card.new
  end

  def edit
  end

  def create
    @card = Card.new(card_params)
    if @card.save
      redirect_to cards_path
    else
      render :new
    end
  end

  def update
    if @card.update(card_params)
      redirect_to cards_path
    else
      render :edit
    end
  end

  def destroy
    @card.destroy
    redirect_to cards_path
  end

  private

  def set_card
    @card = Card.find(params[:id])
  end

  def card_params
    params.require(:card).permit(:original_text, :translated_text)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cards/_form.html.erb
<%= simple_form_for @card do |f| %>

  <%= render 'common/errors', resource: @card %>

<div class="col-md-6">
  <%= f.input :original_text, label: 'Текст' %>
  <%= f.input :translated_text, label: 'Перевод' %>
  <%= f.button :submit, 'Сохранить' %>
  <%= link_to 'Вернуться', cards_path %>
<% end %>
</div>

app/views/cards/edit.html.erb
<h1>Редактировать карточку</h1>

<%= render 'form' %>

app/views/cards/index.html.erb
<h1>Все карточки</h1>

<table class="table table-striped table-bordered">
  <tr class="thead-inverse">
    <th>#</th>
    <th>Название</th>
    <th>Перевод</th>
    <th>Время просмотра</th>
    <th>Изменить</th>
    <th>Удалить</th>
  </tr>

  <% @cards.each do |card| %>
    <tr>
      <td><%= card.id %></td>
      <td><%= card.original_text %></td>
      <td><%= card.translated_text %></td>
      <td><%= card.review_date ? card.review_date.strftime("%d %B %Y %R")
      : 'Not review'  %></td>
      <td><%= link_to 'Изменить', edit_card_path(card) %></td>
      <td><%= link_to 'Удалить', card_path(card),
              method: :delete, data: { confirm: 'Вы уверены?' } %></td>
    </tr>
  <% end %>
</table>

app/views/cards/new.html.erb
<h1>Создать карту</h1>

<%= render 'form' %>

app/views/common/_errors.html.erb
<% if resource.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h2>
        <%= pluralize(resource.errors.count, "error") %> не позволяют сохранить
        данный объект:
      </h2>
      <ul>
        <% resource.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Флэшкарточкер</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul class="nav nav-tabs">
  		<li class="nav-item">
    		<%= link_to 'Флэшкарточкер', root_path, :class => "nav-link navbar-brand active font-weight-bold" %>
  		</li>
  		<li class="nav-item">
        <%= link_to 'Все карточки', cards_path, :class => "nav-link" %>
      </li>
  		<li class="nav-item">
        <%= link_to 'Добавить карточку', new_card_path, :class => "nav-link" %>
      </li>
  	</ul>
  		<%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<p style="font-size: 22px;">
  Первый в мире удобный менеджер флеш-карточек. Именно так.
</p>